spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common # application-common.yml 과 동일한 역할

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

# ...
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create # 개발할때만 사용하기
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod